





//This part calulates the check digit using modulo-11 algorithm
function calc_check_digit(){
   let arr = [];
   let weightage_list = [];
   let digits = document.getElementById("Modulo_11_generate").value;
   let constant = 0;
   let addition =0;
   for(let numbers of digits){
     arr.push(numbers);
     
   }
  
   
   for(let x of arr.reverse()){
     let num = x*(2+constant);
     constant++;
     weightage_list.push(num);
   }
   
   

     function total(){
      
      
      
      for(let a of weightage_list){
        addition += a;
        
        
      }
      
      
      
      weightage_list.splice(0, weightage_list.length);
      
      
      

   }
    
     let  sum = total();
   
      
     let remainder = addition%11;
     
     let check_digit = 11-remainder;
    
     if(arr.length === 0){
      document.getElementById("ans").innerHTML= "Enter the digits";
     }
     else{
      document.getElementById("ans").innerHTML= "Check digit : " + check_digit;
     }
     arr.splice(0, arr.length);
  
     


     
    
   
   
   
}
//This function checks the check digit generated by the modulo-11 check digit
function check_check_digit(){
  let arr = [];
  let weightage_list = [];
  let digits = document.getElementById("check_modulo-11").value;
  let constant = 0;
  let addition =0;
  for(let numbers of digits){
    arr.push(numbers);
    
  }
 

 
  
  for(let x of arr.reverse()){
    let num = x*(1+constant);
    constant++;
    weightage_list.push(num);
  }
  
  
  

    function total(){
     
     
     
     for(let a of weightage_list){
       addition += a;
       
       
     }
     
     
     
    
     weightage_list.splice(0, weightage_list.length);
     
     
     

  }
   
    let  sum = total();
  
     
    let remainder = addition%11;
    
    
    if(remainder === 0 && arr.length > 0 ){
      document.getElementById("ans2").innerHTML= "Check digit is correct ! ";
    }
    
    else if(remainder !== 0){
      document.getElementById("ans2").innerHTML= "Check digit is incorrect :(";
    }
    else if(remainder ===0 && arr.length ===0){
      document.getElementById("ans2").innerHTML= "Enter something :(";
    }

     arr.splice(0, arr.length);
    

    

    
   
  
}

function calc_ISBN(){
let arr =[];
let even = [];
let odd = [];
let det = 2;
let digits = document.getElementById("isbn-13-generate").value;
let x = 0;
let addition =0;


for(let num of digits){
  arr.push(num);
}


for(let x of arr.reverse()){
  if (det%2 ===0) {
    det++;
    even.push(x);
  }
  else{
    det++;
    odd.push(x);
  }
  
}



function calc_odd(){

  for(let x of odd){
    addition +=  parseFloat(x);
  }
  
}

function calc_even(){
  let addition =0 ;
  for(let a of even){
    addition += parseFloat(a);
  }

   x = addition*3;
  
}

let sum_of_odd = calc_odd();
let sum_of_even = calc_even();

let total = addition+x;
let rem = total%10;
let check_digit = 10-rem;




if(arr.length>0){
  document.getElementById("ans3").innerHTML = "ISBN check digit : " + check_digit;
}
else{
  document.getElementById("ans3").innerHTML = "Input the digits:(";
}
    

    
   
  
  
  


}


function check_ISBN(){
  let arr =[];
  let even = [];
  let odd = [];
  let det = 1;
  let digits = document.getElementById("isbn-13-check").value;
  let x = 0;
  let addition =0;
  
  
  for(let num of digits){
    arr.push(num);
  }
  
  
  for(let x of arr.reverse()){
    if (det%2 ===0) {
      det++;
      even.push(x);
    }
    else{
      det++;
      odd.push(x);
    }
    
  }
  
  
  
  function calc_odd(){
  
    for(let x of odd){
      addition +=  parseFloat(x);
    }
    
  }
  
  function calc_even(){
    let addition =0 ;
    for(let a of even){
      addition += parseFloat(a);
    }
  
     x = addition*3;
    
  }
  
  let sum_of_odd = calc_odd();
  let sum_of_even = calc_even();
  
  let total = addition+x;
  let rem = total%10;
  
  if(rem ===0 && arr.length>0){
    document.getElementById("ans4").innerHTML = "Check digit is correct! ";
  }
  else if(rem===0 && arr.length===0){
    document.getElementById("ans4").innerHTML = "PLease input the digits :( ";
  }
  else if(rem!== 0){
    document.getElementById("ans4").innerHTML = "Check digit is incorrect :( ";
  }
  
  
  
  
  
      
  
      
     
    
    
    
  
  
  }